### ISSUE TITLE
Enhance DNS name discovery

### ISSUE THREAD

**Issue by liwenwu-amazon** [aws/aws-application-networking-k8s#10]
Today, the DNS name is  in `message`

```
kubectl get httproute -o yaml
apiVersion: v1
items:
- apiVersion: gateway.networking.k8s.io/v1alpha2
  kind: HTTPRoute
...

  status:
    parents:
    - conditions:
      - lastTransitionTime: "2022-11-07T21:32:40Z"
        message: 'DNS Name: oct25-parking-default-022170a62d6205d58.7d67968.vpc-service-network-svcs.us-west-2.amazonaws.com'
        reason: Reconciled
        status: "True"
        type: httproute
      controllerName: application-networking.k8s.aws/gateway-api-controller
      parentRef:
        group: gateway.networking.k8s.io
        kind: Gateway
        name: oct25-my-hotel
...
```

This should be enhanced 

* use annotation 
* or part of "HOSTNAMES"
```
kubectl get httproute
NAME            HOSTNAMES   AGE
oct25-parking               4m43s
```
