### ISSUE TITLE
Controller is not following `HTTPRouteRule` spec, if no rule is matched a 404 must be returned

### ISSUE THREAD

**Issue by aaroniscode** [aws/aws-application-networking-k8s#102]
When deploying the [examples/rate-route-path.yaml](https://github.com/aws/aws-application-networking-k8s/blob/main/examples/rate-route-path.yaml), two rules are specified:

```
  rules:
  - backendRefs:  
    - name: parking
      kind: Service
      port: 8090
    matches:
    - path:
        type: PathPrefix
        value: /parking
  - backendRefs:
    - name: review
      kind: Service
      port: 8090
    matches:
    - path:
        type: PathPrefix
        value: /review
```

however performing a request to `/` results in a route to the `parking` service.

According to the [`HTTPRouteRule` spec](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1beta1.HTTPRouteRule):

> When no rules matching a request have been successfully attached to the parent a request is coming from, a HTTP 404 status code MUST be returned.

Looking at the Lattice Config it's creating a default action to send to the first service in the rule list which is not compliant with the spec and not what's expected based upon the `HTTPRoute` rule definition above.

<img width="1119" alt="Screen Shot 2023-02-24 at 5 20 35 PM" src="https://user-images.githubusercontent.com/1521726/221324557-a5850412-a910-46e8-b232-db6336dd5d7b.png">
