### ISSUE TITLE
Gateway and HTTPRoute unable to be deleted -- stuck finalizing

### ISSUE THREAD

**Issue by ellistarn** [aws/aws-application-networking-k8s#115]
### Reproduction steps:
1. Create gateway and gateway class
2. Delete gateway class
3. Delete gateway (stuck deleting)
4. Delete HTTPRoute (stuck deleting)
5. Observe finalizer still on resource.

This log line looks like the culprit.
```
gateway-api-controller-6d499b898c-nq4sr manager 2023-03-05T01:56:33.540Z	INFO	controller.gateway	Ignore it since not link to any gatewayclass	{"reconciler group": "gateway.networking.k8s.io", "reconciler kind": "Gateway", "name": "carverspring-2-v1bayfdckt", "namespace": "default"}
```

```
- apiVersion: gateway.networking.k8s.io/v1alpha2
  kind: HTTPRoute
  metadata:
    creationTimestamp: "2023-03-03T23:47:55Z"
    deletionGracePeriodSeconds: 0
    deletionTimestamp: "2023-03-04T02:28:55Z"
    finalizers:
    - httproute.k8s.aws/resources
```
