### ISSUE TITLE
Vanity DNS support

### ISSUE THREAD

**Issue by liwenwu-amazon** [aws/aws-application-networking-k8s#16]
Today,  after HTTPRoute CREATE reconcile, it gets an long lattice DNS name,  This PR allows K8S user to specify a vanity name for the service. e.g.

* the HTTPRoute name is the vanity name
* or the "hostname" value of HTTPRoute is the vanity name

```
 kubectl get httproute -o yaml
apiVersion: v1
items:
- apiVersion: gateway.networking.k8s.io/v1alpha2
  kind: HTTPRoute
...
status:
    parents:
    - conditions:
      - lastTransitionTime: "2022-10-31T02:12:15Z"
        message: 'DNS Name: oct30-inventory-default-065bc76ad6f66c05e.7d67968.lattice-svcs-prod.us-west-2.on.aws'
        reason: Reconciled
        status: "True"
        type: httproute
```
