### ISSUE TITLE
bug: Target not automatically registered in Target Group

### ISSUE THREAD

**Issue by zhuoyang** [aws/aws-application-networking-k8s#244]
I am seeing errors like this in gateway api controller logs and the target is not automatically registered in target group

```
E0511 21:55:34.435754       1 request.go:539] Failed request: VpcLattice/ListTargets, Payload: {  TargetGroupIdentifier: ""}, Error: InvalidParameter: 1 validation error(s) found.
93
- minimum field size of 17, ListTargetsInput.TargetGroupIdentifier.
```

Please advise, will provide more info upon request.

P/S: I've already created a support ticket in AWS (Case ID 12717202271), posting this here for visibility.

**Comment by solmonk** [comment]
Can you provide us more details (like config yaml) so that we can reproduce this issue? More logs would be helpful as well.

**Comment by zhuoyang** [comment]
Here's the full [logs](https://gist.github.com/zhuoyang/2ca07446013da48eba35fc67ef230dc0)
About the config, I didn't do much custom configuration other than:
1. Putting all of the related resources in "vpc-lattice" namespace
2. Setting service account to use the role I've created
3. Creating a gateway in default namespace, then allowing all namespace to access the gateway
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  annotations:
    application-networking.k8s.aws/lattice-vpc-association: 'true'
  labels:
    app.kubernetes.io/instance: stag-eks-2-vpc-lattice
  name: lattice-gateway
  namespace: default
spec:
  gatewayClassName: amazon-vpc-lattice
  listeners:
    - allowedRoutes:
        namespaces:
          from: All
      name: http
      port: 80
      protocol: HTTP
```
