### ISSUE TITLE
bug: correctly infer namespace of HTTPRoute backendRef

### ISSUE THREAD

**Issue by solmonk** [aws/aws-application-networking-k8s#251]
### To reproduce
Create gateway in `default`, service in `non-default` namespace.

Create the following httproute in `non-default` namespace:
```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: inventory
spec:
  parentRefs:
  - name: my-hotel
    namespace: default
    sectionName: http
  rules:
  - backendRefs:
    - name: inventory-ver1
      kind: Service
      port: 8090
      weight: 10
```

### Current behavior
This leads to the following error when registering targets:
```
I0515 19:08:07.547245   87545 model_build_targets.go:107] errmsg: Build Targets failed because K8S service default/inventory-ver1 does not exist
I0515 19:08:07.547252   87545 model_build_targetgroup.go:162] Error buildTargets for backend ref service {{{0xc000b5c3b0 0xc000b5c3c0 inventory-ver1 <nil> 0xc000bbf240} 0xc000bbf244} []}
```
Seems the controller infers `default` namespace by default. [example1](https://github.com/aws/aws-application-networking-k8s/blob/main/pkg/gateway/model_build_targetgroup.go#L143) [example2](https://github.com/aws/aws-application-networking-k8s/blob/main/pkg/gateway/model_build_targetgroup.go#L281)

### What to expect
Since the route itself is in `non-default` namespace, the backendRefs [should also implicitly refer to](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io%2fv1beta1.BackendObjectReference) `non-default`.

### Related
Possibly related to #244
