### ISSUE TITLE
[Bug] Remove `healthCheck` section in TargetGroupPolicy cannot trigger controller to reconcile TargetGroupPolicy

### ISSUE THREAD

**Issue by zijun726911** [aws/aws-application-networking-k8s#369]
For example, If I have a full connectivity setup gateway, route, service, deployment as well as TargetGroupPolicy.

I applied the following TargetGroupPolicy first with healthcheck:
```
apiVersion: application-networking.k8s.aws/v1alpha1
kind: TargetGroupPolicy
metadata:
  name: test-policy
spec:
  targetRef:
    group: “”
    kind: Service
    name: my-http-server
  protocol: HTTP
  healthCheck:
    enabled: true
    intervalSeconds: 5
    timeoutSeconds: 1
    healthyThresholdCount: 3
    unhealthyThresholdCount: 2
    path: “/”
    port: 9000
    protocol: HTTP
     protocolVersion: HTTP2
     statusMatch: “200”
```

Then I hope to delete the health check config by remove the `healthCheck` section:
```
apiVersion: application-networking.k8s.aws/v1alpha1
kind: TargetGroupPolicy
metadata:
  name: test-policy
spec:
  targetRef:
    group: “”
    kind: Service
    name: my-http-server
  protocol: HTTP
```

But controller actually didn't invoke lattice api to update to disable the health check 

( Explicitly set `healthCheck: enabled: true` could work)
