### ISSUE TITLE
Not able to create multiple backendRefs for same service listning on 2 different ports

### ISSUE THREAD

**Issue by chaitanyaavi** [aws/aws-application-networking-k8s#444]
Not able to deploy service with 2 different backendRefs for the same service on 2 different ports.

Here is the HTTPRoute config I used:
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: backend-api-routes
  namespace: backend
spec:
  parentRefs:
  - name: backend-gateway
    kind: Gateway
    namespace: default
    sectionName: http
  rules:
  - backendRefs:
    - name: apiserver     
      kind: Service
      namespace: backend
      port: 8088
    matches:
    - path:
        type: PathPrefix
        value: /graphql
  - backendRefs:
    - name: apiserver      
      kind: Service
      namespace: backend
      port: 8080
    matches:
    - path:
        type: PathPrefix
        value: /
  
```
This creates a target group with a single target for port 8088. If I need to change the name of the second Backend ref, how can I provide the service name for that reference?
