### ISSUE TITLE
Redesign ServiceExport spec

### ISSUE THREAD

**Issue by solmonk** [aws/aws-application-networking-k8s#592]
An extension of #365 

The controller is not yet allowing exporting TG for use in routes other than HTTPRoute. As more route types (TLSRoute, TCPRoutes, and more) are coming, we need a fundamental solution to support all route types.

An original suggestion was to create all types of target groups when exported - but it is technically a waste of resource, and actually not compatible with common use cases.

For example, let's say a service has 2 exported ports - 80 serves plaintext HTTP, and 8081 serves GRPC.

To support all types of traffic we need 2 different types of target groups to be attached to 2 different routes.

Now that we have our own ServiceExport spec, we could define something like this on ServiceExport, and be explicit on which target groups are to be exported:
```
spec:
  exportedPorts:
  - port: 80 # this is equivalent to backendref port
    routeType: HTTP
  - port: 8081
    routeType: GRPC
```

The following behavior is required:
* For each exported port, create target group to be used with relevant route type
* When importing service, backendRef port must match the exported port.
* For backwards compatibility, keep the old behavior when no exportedPort is defined (export all ports to HTTP target group.)
