### ISSUE TITLE
Single VPC Lattice Service with multiple listeners (each explicitly linked to a different `backendRef`)

### ISSUE THREAD

**Issue by HannesBBR** [aws/aws-application-networking-k8s#644]
Hi,

One of our applications running in k8s accepts both GRPC and HTTP traffic (its pods have different containers with a different port). To handle traffic for this application, we have 2 k8s services:
- `service-rest` => forwards traffic to the port of the rest-container
- `service-grpc` => forwards traffic to the port of the grpc-container

Our current ingress into this k8s application is an ALB with two listeners that forward traffic to the respective k8s service, based on the port:
- `443` listener => forwards to target group `tg-rest`, which sends traffic to the `service-rest` in k8s (targets are managed by the AWS load-balancer controller)
- `50051` listener => forwards to target group `tg-grpc`, which sends traffic to the `service-grpc` in k8s (targets are managed by the AWS load-balancer controller)

The domain name used by the clients is the same for both REST and GRPC traffic, and they choose the respective ALB listener port depending on whether they want to talk REST or GRPC.

As we are onboarding services into VPC Lattice, we'd now like the achieve the same kind of setup with VPC Lattice for this application:
- A single VPC Lattice service with a custom domain name
- 2 listeners in this VPC Lattice service
    -  `443` listener => forward all traffic on this port to target group `vpc-lattice-tg-rest`
    - `50051` listener => forward all traffic on this port to target group `vpc-lattice-tg-grpc`

I have tried some things to achieve this setup using the Gateway API controller, but I didn't find a way to do this:
- Two different `HTTPRoute` resources with the same name, but a different `sectionName` in the `parentRefs` property and a different `backendRef` service:
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: test-application
spec:
  hostnames:
    - test-app.test.com
  parentRefs:
    - name: test-service-network
      sectionName: rest
      namespace: aws-application-networking-system
  rules:
    - backendRefs:
      - name: testapp-service-rest
         kind: Service
         port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: test-application
spec:
  hostnames:
    - test-app.test.com
  parentRefs:
    - name: test-service-network
      sectionName: grpc
      namespace: aws-application-networking-system
  rules:
    - backendRefs:
      - name: testapp-service-grpc
         kind: Service
         port: 50051
```

   => this creates a single VPC Lattice service with one listener and two target groups. However it causes the controller to periodically flipflop/overwrite the (single) listener of the service between the two ports related to the two `sectionNames`, instead of adding a second listener to the service that would then forward traffic to its respective targetgroup.

- A single `HTTPRoute` resource, with two `parentRefs` and two `backendRefs`:
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: test-application
spec:
  hostnames:
    - test-app.test.com
  parentRefs:
    - name: test-service-network
      sectionName: rest
      namespace: aws-application-networking-system
    - name: test-service-network
      sectionName: grpc
      namespace: aws-application-networking-system
  rules:
    - backendRefs:
      - name: testapp-service-rest
         kind: Service
         port: 80
      - name: test-app-service-grpc
         kind: Service
         port: 50051
```

   => the result is a single VPC Lattice service with two listeners, and two target groups. However, the rules in each of the two listeners basically split traffic evenly between the two created target groups, while we'd like to have all traffic for a listener be forwarded to the 'correct' target group only.

Ideally, I would hope something like this would be possible, where you explicitly define which backendRef should be used by which listener/parent:
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: test-application
spec:
  hostnames:
    - test-app.test.com
  parentRefs:
    - name: test-service-network
      sectionName: rest
      namespace: aws-application-networking-system
    - name: test-service-network
      sectionName: grpc
      namespace: aws-application-networking-system
  rules:
    - backendRefs:
      - name: testapp-service-rest
         kind: Service
         port: 80
         parent: rest --> some kind of ref to a parent above
      - name: test-app-service-grpc
         kind: Service
         port: 50051
         parent: grpc --> some kind of ref to a parent above
```

But perhaps there already is another way of achieving the situation described above with the existing controller?
Many thanks!

**Comment by zijun726911** [comment]
Could you help me to try this way and let me know does this work for you? Thank you so much! Maybe you can create one HTTPRoute and one GRPCRoute:


```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: test-application
spec:
  hostnames:
    - test-app.test.com
  parentRefs:
    - name: test-service-network
      sectionName: rest
      namespace: aws-application-networking-system
  rules:
    - backendRefs:
      - name: testapp-service-rest
         kind: Service
         port: 80
```


```
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GRPCRoute
metadata:
  name: test-application
spec:
  hostnames:
    - test-app.test.com
  parentRefs:
    - name: test-service-network
      sectionName: grpc
      namespace: aws-application-networking-system
  rules:
    - backendRefs:
         - name: test-app-service-grpc
            kind: Service
            port: 50051
```

https://github.com/aws/aws-application-networking-k8s/blob/55532132df0bda0d10e64192ff5c8a6a88860e4a/docs/api-types/grpc-route.md#L73

**Comment by HannesBBR** [comment]
Hi, thanks for your response! I forgot to mention that I also tried this option already indeed, but what then seems to happen is:
- 1 VPC Lattice Service is created
- 2 Target groups are created (one for grpc, one for rest)
- 1 Listener (GRPC) is created in the service (forwarding traffic to the GRPC target group)

When describing the `HTTPRoute` resource the message says :
```
Message:  error during service synthesis failed ServiceManager.Upsert test-app-test-app due to service test-app/test-app had a conflict: Found existing resource with conflicting service name: arn:aws:vpc-lattice:eu-central-1:123456789:service/svc-12345789`
```
So it looks like the controller tries to create a new Lattice service, and stops because there already is a service with that name. Ideally for my use case, it would then rather acknowledge that a service for that name already exists and then adds a new listener to that service based on the `backendRef` and `parentRef` that are configured in the `HTTPRoute`. Hard though to assess what kind of impact such a change would have in the whole flow.

**Comment by zijun726911** [comment]
Hi @HannesBBR , thanks for your reply. The current controller version don't support your use case to translate k8s resource into 2 listeners in a same lattice Service and 2 listeners route traffic to different target groups. However, the vpc lattice itself did support that set up, for example:
<img width="1171" alt="image" src="https://github.com/aws/aws-application-networking-k8s/assets/32318664/5ee4726e-91be-49b1-9486-dd7d326fb56c">

(Just currently no k8s resource representation can translate to this lattice resource setup.)
And for your suggest: `parent: grpc --> some kind of ref to a parent above` I think it's not in the [gateway api spec HTTPRoute](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.HTTPRouteRule), and seems gateway api HTTPRoute don't have a proper way to represent it.


To immediately unblock your use case, probably you can try this workaround: Use K8s ServiceExport  and k8s TargetGroupPolicy only. Don't create any k8s Gateway, k8s HTTPRoute, k8s ServiceImport. Don't use the controller to manage the VPC Lattice service. Instead, manage the VPC Lattice service outside of the k8s. i.e., Use the aws console, CloudFormation, Terraform to create the VPC Lattice service network and service.

For example, following this steps:
0. Make sure the aws gateway api controller, `testapp-service-rest` and `testapp-service-grpc` running in your k8s clusters
1.  Create K8s ServiceExport  and k8s TargetGroupPolicy:
```
apiVersion: application-networking.k8s.aws/v1alpha1
kind: ServiceExport
metadata:
  name: testapp-service-rest
  annotations:
    application-networking.k8s.aws/federation: "amazon-vpc-lattice"
    application-networking.k8s.aws/port: "80"
```


```
apiVersion: application-networking.k8s.aws/v1alpha1
kind: TargetGroupPolicy
metadata:
    name: tg-policy-for-testapp-service-rest
spec:
    targetRef:
        group: application-networking.k8s.aws
        kind: ServiceExport
        name: testapp-service-rest
    protocol: HTTP
    protocolVersion: HTTP1
```

```
apiVersion: application-networking.k8s.aws/v1alpha1
kind: ServiceExport
metadata:
  name: testapp-service-grpc
  annotations:
    application-networking.k8s.aws/federation: "amazon-vpc-lattice"
    application-networking.k8s.aws/port: "50051"
```


```
apiVersion: application-networking.k8s.aws/v1alpha1
kind: TargetGroupPolicy
metadata:
    name: tg-policy-for-testapp-service-grpc
spec:
    targetRef:
        group: application-networking.k8s.aws
        kind: ServiceExport
        name: testapp-service-grpc
    protocol: HTTP
    protocolVersion: GRPC
```
2. Go to the aws vpc lattice target group console, you should be able to see the TargetGroups with name `k8s-<namespace>-testapp-service-http-<randomstring>` and `k8s-<namespace>-testapp-service-grpc-<randomstring>` has been created
3.  In the console (or CloudFormation, Terraform), manually create VPC Lattice Service and 2 listener: 
  - One https:443 vpc lattice listener with a rule route to the `k8s-<namespace>-testapp-service-http-<randomstring>` Target Group
  - And another HTTP(S):50051 vpc lattice listener route to the `k8s-<namespace>-testapp-service-grpc-<randomstring>` Target Group
