### ISSUE TITLE
Lattice listener not listing rules for all the paths listed in the HTTPRoute resource

### ISSUE THREAD

**Issue by vijayansarathy** [aws/aws-application-networking-k8s#75]
I used the HTTPRoute below:

```
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: frontend
  namespace: default
spec:
  parentRefs:
  - name: eks-store-network
    sectionName: http 
    namespace: default
  rules:
  - backendRefs:  
    - name: frontend-svc
      kind: Service
      port: 3000
      namespace: default
    matches:
    - path:
        type: PathPrefix
        value: /summary    
    - path:
        type: PathPrefix
        value: /popular
```
I expected the corresponding Listener created under VPC Lattice to have separate rules for "/summary" and "/popular". But, I see the listener has a default rule and just one other non-default rule that matched "/summary". There no rule specific to the path "/popular"

```
aws lattice --endpoint $ENDPOINT list-rules --listener-identifier $LISTENER_ID --service-identifier $SERVICE_ID     
{
    "items": [
        {
            "arn": "arn:aws:vpc-lattice:us-west-2:937351930975:service/svc-0f521522304b8db18/listener/listener-0a69653897eba06e7/rule/rule-0565e9f746a9fd13a",
            "createdAt": "2022-12-20T00:51:12.734000+00:00",
            "id": "rule-0565e9f746a9fd13a",
            "isDefault": true,
            "lastUpdatedAt": "2022-12-20T00:51:12.734000+00:00",
            "name": "default"
        },
        {
            "arn": "arn:aws:vpc-lattice:us-west-2:937351930975:service/svc-0f521522304b8db18/listener/listener-0a69653897eba06e7/rule/rule-0ebabd8dba993eaa4",
            "createdAt": "2022-12-20T03:01:32.023000+00:00",
            "id": "rule-0ebabd8dba993eaa4",
            "isDefault": false,
            "lastUpdatedAt": "2022-12-20T03:01:33.689000+00:00",
            "name": "k8s-1671505290-rule-1"
        }
    ]
}
```

```
RULE_ID="rule-0ebabd8dba993eaa4"         
aws lattice --endpoint $ENDPOINT get-rule --rule-identifier $RULE_ID --listener-identifier $LISTENER_ID --service-identifier $SERVICE_ID

{
    "action": {
        "forward": {
            "targetGroups": [
                {
                    "targetGroupIdentifier": "tg-07ee612f7751f2293",
                    "weight": 1
                }
            ]
        }
    },
    "arn": "arn:aws:vpc-lattice:us-west-2:937351930975:service/svc-0f521522304b8db18/listener/listener-0a69653897eba06e7/rule/rule-0ebabd8dba993eaa4",
    "createdAt": "2022-12-20T03:01:32.023000+00:00",
    "id": "rule-0ebabd8dba993eaa4",
    "lastUpdatedAt": "2022-12-20T03:01:33.689000+00:00",
    "match": {
        "httpMatch": {
            "headerMatches": [],
            "pathMatch": {
                "caseSensitive": true,
                "match": {
                    "prefix": "/summary"
                }
            }
        }
    },
    "name": "k8s-1671505290-rule-1",
    "priority": 1
}

```
