### ISSUE TITLE
Controller doesn't create a service when using namespace other than default in HTTPRoute

### ISSUE THREAD

**Issue by vijayansarathy** [aws/aws-application-networking-k8s#95]
I used this manifest to create a HTTPRoute.

```
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: backend
  namespace: store
spec:
  parentRefs:
  - name: eks-store-network
    sectionName: http 
    namespace: store
  rules:
  - backendRefs:  
    - name: backend-svc
      kind: Service
      port: 3000
      namespace: store
    matches:
    - path:
        type: PathPrefix
        value: /popular
    - path:
        type: PathPrefix
        value: /summary
```

This does not lead to the creation of a Lattice Service. The logs from the controller are shown below. If the change the namespace to default, it works.

```
2023-02-22T02:31:03.477Z	INFO	controller.httproute	HTTPRouteReconciler	{"reconciler group": "gateway.networking.k8s.io", "reconciler kind": "HTTPRoute", "name": "backend", "namespace": "store"}
2023-02-22T02:31:03.477Z	INFO	controller.service	ServiceReconciler	{"reconciler group": "", "reconciler kind": "Service", "name": "backend-svc", "namespace": "store"}
```

There are no further logs that a indicate a service was created.
