### ISSUE TITLE
Canary traffic shifting does not work when using 1+ rules in HTTPRoute

### ISSUE THREAD

**Issue by vijayansarathy** [aws/aws-application-networking-k8s#96]
This is related to https://github.com/aws/aws-application-networking-k8s/issues/75 but wanted create this separately to call out the implications of not handling 1+ rules.
Canary shifting of traffic breaks due to the fact that Lattice does not pick up all the path-based rules.

The following is the HTTPRoute I used.
Here, the /summary endpoint returns different results for v1 and v2.

```
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: backend-canary
  namespace: default
spec:
  parentRefs:
  - name: eks-store-network
    sectionName: http 
    namespace: default
  rules:
  - backendRefs:  
    - name: backend-v1-svc
      kind: Service
      port: 3000
      namespace: default
      weight: 25
    - name: backend-v2-svc
      kind: Service
      port: 3000
      namespace: default      
      weight: 75
    matches:
    - path:
        type: PathPrefix
        value: /popular
    - path:
        type: PathPrefix
        value: /summary
```
When I look at the listener using the following CLI
```
aws lattice --endpoint $ENDPOINT list-rules --listener-identifier $LISTENER_ID --service-identifier $SERVICE_ID
```
gives the following output
```
{
    "items": [
        {
            "arn": "arn:aws:vpc-lattice:us-west-2:937351930975:service/svc-070486ef14a0e8348/listener/listener-09d05a6365bd3e3c1/rule/rule-0913b01117b721751",
            "createdAt": "2023-02-22T05:02:49.110000+00:00",
            "id": "rule-0913b01117b721751",
            "isDefault": true,
            "lastUpdatedAt": "2023-02-22T05:02:49.110000+00:00",
            "name": "default"
        },
        {
            "arn": "arn:aws:vpc-lattice:us-west-2:937351930975:service/svc-070486ef14a0e8348/listener/listener-09d05a6365bd3e3c1/rule/rule-01de45c95a0bb8f8a",
            "createdAt": "2023-02-22T05:02:49.377000+00:00",
            "id": "rule-01de45c95a0bb8f8a",
            "isDefault": false,
            "lastUpdatedAt": "2023-02-22T05:02:51.621000+00:00",
            "name": "k8s-1677042167-rule-1"
        }
    ]
}
```

The first rule is the default that sends 100% the responses to the target group associated with v1 of the service.

```
RULE_ID=rule-0913b01117b721751 
aws lattice --endpoint $ENDPOINT get-rule --rule-identifier $RULE_ID --listener-identifier $LISTENER_ID --service-identifier $SERVICE_ID
```
```
{
    "action": {
        "forward": {
            "targetGroups": [
                {
                    "targetGroupIdentifier": "tg-07c009c6ed1ff42a3",
                    "weight": 1
                }
            ]
        }
    },
    "arn": "arn:aws:vpc-lattice:us-west-2:937351930975:service/svc-070486ef14a0e8348/listener/listener-09d05a6365bd3e3c1/rule/rule-0913b01117b721751",
    "createdAt": "2023-02-22T05:02:49.110000+00:00",
    "id": "rule-0913b01117b721751",
    "isDefault": true,
    "lastUpdatedAt": "2023-02-22T05:02:49.110000+00:00",
    "name": "default"
}
```
The second rule is the weighted one but it takes effect only if the request path is /popular.
As a result, requests to the endpoint /summary are all routed to v1 of the service.

```
RULE_ID=rule-01de45c95a0bb8f8a
aws lattice --endpoint $ENDPOINT get-rule --rule-identifier $RULE_ID --listener-identifier $LISTENER_ID --service-identifier $SERVICE_ID
```
```
{
    "action": {
        "forward": {
            "targetGroups": [
                {
                    "targetGroupIdentifier": "tg-07c009c6ed1ff42a3",
                    "weight": 25
                },
                {
                    "targetGroupIdentifier": "tg-07792a965fe50fda2",
                    "weight": 75
                }
            ]
        }
    },
    "arn": "arn:aws:vpc-lattice:us-west-2:937351930975:service/svc-070486ef14a0e8348/listener/listener-09d05a6365bd3e3c1/rule/rule-01de45c95a0bb8f8a",
    "createdAt": "2023-02-22T05:02:49.377000+00:00",
    "id": "rule-01de45c95a0bb8f8a",
    "lastUpdatedAt": "2023-02-22T05:02:51.621000+00:00",
    "match": {
        "httpMatch": {
            "headerMatches": [],
            "pathMatch": {
                "caseSensitive": true,
                "match": {
                    "prefix": "/popular"
                }
            }
        }
    },
    "name": "k8s-1677042167-rule-1",
    "priority": 1
}
```
